### PR TITLE
Update flow to 0.96 and fix flow error

### LINKED ISSUE #163: Flow error with flow-bin@0.95.1
There's a Flow error with `flow-bin@0.95.1`.

### Type of issue
Flow type error

### Description

Flow error is gone.

### Current behavior

Screen Shot 2019-03-19 at 2 47 22 PM

### Expected behavior

No error

### Your environment
* fusion-plugin-apollo version:

* Node.js version (`node --version`):

* npm version (`npm --version`):

* Operating System:

### PR DESCRIPTION
**Pull request by KevinGrandon**
The upgrade resulted in an error like: 

image

Casting to a string seems to fix it.

Fixes #163

### CODE REVIEW

File: src/plugin.js [hunk 1]
```diff
@@ -100,7 +100,7 @@ export default (renderFn: Render) =>
           const serialized = JSON.stringify(initialState);
           const script = html`
             <script type="application/json" id="__APOLLO_STATE__">
-              ${serialized}
+              ${String(serialized)}
```
Comment (KevinGrandon) [inline src/plugin.js]: Hmm, or is this going to cause issues with the `html` tagged template functionality? 🤔

Comment (KevinGrandon) [reply src/plugin.js]: No, I guess `serialized` should be a string after all given the JSON.stringify call above.

**Comment by KevinGrandon** [comment]
!merge
